from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_referee(object):
    def setupUi(self, referee):
        referee.setObjectName("referee")
        referee.resize(640, 240)
        self.centralwidget = QtWidgets.QWidget(referee)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.getGamesButton = QtWidgets.QPushButton(self.centralwidget)
        self.getGamesButton.setObjectName("getGamesButton")
        self.verticalLayout.addWidget(self.getGamesButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gamesList = QtWidgets.QComboBox(self.centralwidget)
        self.gamesList.setObjectName("gamesList")
        self.verticalLayout.addWidget(self.gamesList)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.chooseGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseGameButton.setObjectName("chooseGameButton")
        self.verticalLayout.addWidget(self.chooseGameButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hostLabel = QtWidgets.QLabel(self.centralwidget)
        self.hostLabel.setObjectName("hostLabel")
        self.horizontalLayout.addWidget(self.hostLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.hostResultInput = QtWidgets.QTextEdit(self.centralwidget)
        self.hostResultInput.setObjectName("hostResultInput")
        self.horizontalLayout.addWidget(self.hostResultInput)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.guestResultInput = QtWidgets.QTextEdit(self.centralwidget)
        self.guestResultInput.setObjectName("guestResultInput")
        self.horizontalLayout.addWidget(self.guestResultInput)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.guestLabel = QtWidgets.QLabel(self.centralwidget)
        self.guestLabel.setObjectName("guestLabel")
        self.horizontalLayout.addWidget(self.guestLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.applyButton = QtWidgets.QPushButton(self.centralwidget)
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout.addWidget(self.applyButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        referee.setCentralWidget(self.centralwidget)

        self.retranslateUi(referee)
        QtCore.QMetaObject.connectSlotsByName(referee)

    def retranslateUi(self, referee):
        _translate = QtCore.QCoreApplication.translate
        referee.setWindowTitle(_translate("referee", "Referee"))
        self.getGamesButton.setText(_translate("referee", "Get games list"))
        self.chooseGameButton.setText(_translate("referee", "Choose game"))
        self.hostLabel.setText(_translate("referee", "Host"))
        self.guestLabel.setText(_translate("referee", "Guest"))
        self.applyButton.setText(_translate("referee", "Apply result"))
